pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r docs/ .public
  - mv .public public
  - apt install docsify
  - docsify serve public/
  artifacts:
    paths:
    - public
  only:
  - master
